### ISSUE TITLE
Maybe a typo in your example

### ISSUE THREAD

**Issue by papricasix** [monkeycz/rustlib-analysis-fix#1]
There seems to be a typo in your example:

`rustlib-analysis-fix /Users/<Username>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src ...`

should be actually:

`rustlib-analysis-fix /Users/<Username>/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust ...`

Otherwise VSCode tries to open files from `.../src/src/...`

(I'm using `stable-x86_64-apple-darwin`, `rustc 1.24.1 (d3ae9a9e0 2018-02-27)`)

Btw. thx for this nice tool! 👍

**Comment by monkeycz** [comment]
@papricasix Sorry, I didn't say it clearly. My example is for nightly build version. For stable build version, your command line is right.
